### ISSUE TITLE
Using information from a void callback function

### ISSUE THREAD

**Issue by jreyes81** [jreyes81/rescuerobot#7]
### Expected behavior
------------------------------------- On "dev" branch ----------------------------------
https://github.com/jreyes81/rescuerobot/blob/a72485931a3d3255ab3ef9f79667d87538de3a36/arduino/HCSR04%20/radar_teen_hc/micro_servo/micro_servo.ino#L43
In this line I create a global variable that will hold state information on having the micro servo sweep and stop sweeping. I then try to have the callback function below to populate the global variable from a topic I am subscribing:
`void radar_swp_cb( const std_msgs::Float32& state_msg){
  sweep_state = state_msg.data; // Contains either 0 or 1. 0 for sweep and 1 for not sweep
  //return 0;
}`

I then try to use the information in the sweep_state variable in a loop to write to the micro servo on its position. The code below is a sample from my actual code:
`void loop() {
if (sweep_state == 1){`

I expect this process to work but somewhere along these lines, it wasn't working as well. I suspect the void callback function is the issue and thought about implementing a sort of class, or object oriented process to get this to work.
### Actual behavior
The global variable sweep_state, seems to not get overwritten with the new information coming from the message topic I am subscribing to 

### Steps to reproduce the behavior
The link below is where I have my actual code. 
https://github.com/jreyes81/rescuerobot/blob/dev/arduino/HCSR04%20/radar_teen_hc/micro_servo/micro_servo.ino

**Comment by jay3ss** [comment]
Callback functions only get executed when they receive a message. Maybe it's subscribed to the wrong topic, you're publishing to the wrong topic, nothing is being published, or you're not publishing a `0` or a `1`. Try manually publishing a `1` on the `scan_once_to_whls` topic from the terminal and see if it does what you want. Also, add a `Serial.write` that you can see using the serial monitor in that section of your `loop()` function to see if it gets activated.

This might be a good place to use a `bool` instead of an `int` (semantically, it makes more sense). You can publish `bool` s using the `std_msgs::Bool` message type.

**Comment by jreyes81** [comment]
So if I have a global variable initialized, and try to have the variable change whenever the call back function receives information; will the variable be able to contain the information from the callback function so that I can use it in another function? Its kind of like i want to use the "self" method that python has when i use a class. Yeah I am also trying to use bool's in another copy of my code

**Comment by jay3ss** [comment]
Yes, that variable will hold the value from the callback. Did you try what I suggested?

**Comment by jreyes81** [comment]
Okay. Yeah I checked to see if i was publishing the right information and subscribing to it. It looked like I was but for someone reason, the information did not alternate to what I wanted to. It could be because the way that I have it set up maybe. I will keep working on it to see where the issue is exactly
